name: ml_project_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - pip
  - pip:
      - black
      - isort
      - flake8
      - pytest
