name: Style Test

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          auto-activate-base: true
          activate-environment: ml_project_env

      - name: Verify Environment
        run: |
          conda info --envs
          which python
          which isort
          which black
          which flake8
          isort --version
          black --version
          flake8 --version

      - name: Run Style Checks
        run: |
          isort src/ tests/ scripts/
          black src/ tests/ scripts/
          flake8 src/ tests/ scripts/
