name: Style Test

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          activate-environment: ml_project_env
          auto-activate-base: false

      - name: Debug Conda Activation
        run: |
          source ~/.bashrc
          conda activate ml_project_env
          echo "Python location: $(which python)"
          echo "isort location: $(which isort)"
          echo "Environment packages:"
          conda list

      - name: Run Style Checks
        run: |
          source ~/.bashrc
          conda activate ml_project_env
          isort src/ tests/ scripts/
          black src/ tests/ scripts/
          flake8 src/ tests/ scripts/
