name: Style Test

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          auto-activate-base: false
          activate-environment: ml_project_env
          python-version: "3.9"

      - name: Verify Environment
        run: |
          eval "$(conda shell.bash hook)"
          conda activate ml_project_env
          conda info --envs
          which python
          python -m pip list

      - name: Run Style Checks
        run: |
          conda run -n ml_project_env --no-capture-output isort src/ tests/ scripts/
          conda run -n ml_project_env --no-capture-output black src/ tests/ scripts/
          conda run -n ml_project_env --no-capture-output flake8 src/ tests/ scripts/

      - name: Debug Conda Environment
        run: |
          conda run -n ml_project_env --no-capture-output conda info --envs
          conda run -n ml_project_env --no-capture-output conda list
