name: Style Test

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          auto-activate-base: false

      - name: Activate Conda Environment
        run: |
          conda activate ml_project_env
          conda info --envs
          conda list
          which python
          which isort
          which black
          which flake8

      - name: Run Style Checks
        run: |
          conda activate ml_project_env
          isort src/ tests/ scripts/
          black src/ tests/ scripts/
          flake8 src/ tests/ scripts/
