name: Unit and Functional Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: env.yml
          activate-environment: ml_env

      - name: Install Package in Dev Mode
        run: pip install -e .

      - name: Run Pytest
        run: pytest -v tests
